### PR TITLE
fix checkbox not working in component array

### PR DESCRIPTION
**Pull request by kevinlinxp**
@loopyluke

### CODE REVIEW

**Comment by Anthropic** [comment]
@kevinlindev interesting changes, I assume meant for your fork? I am already looking at ways to provide better access to array indexes for use in keys and field names/ids, I do hope it wont take too much longer, but time is short unfortunately.

**Comment by kevinlinxp** [comment]
Hi @Anthropic, yes that's for our fork, sorry for the confusion.
It would really be great if we can have a better way to access the array context :)
And we also found we need to be careful of using "item" as loop variable in our templates because it seems has some conflict with the "item" internally used by the schemaform array directive.

**Comment by Anthropic** [comment]
@kevinlindev the next update will be based off the webpack babel branches in asf and bootstrap decorator as well as the new json-schema-form-core repo. One developer Joel has added arrayIndices (for dealing with arrays in arrays), but we found it hard to access in all locations so he is looking at a way to add it to the builder itself. Hopefully we can find a way to make arrays a lot more stable soon :)

**Comment by Anthropic** [comment]
Oh and good to finally have some other developers using the framework in the same timezone!

**Comment by kevinlinxp** [comment]
@Anthropic thanks bro, that sounds a exciting update. Nice to meet you here :-D

**Pull request closed without merging**
